### ISSUE TITLE
error npm run start

### ISSUE THREAD

**Issue by monchichis** [Bangik/chatgpt-wa-bot#5]
ada error ini gan. maksudnya gimana ya apa ada library yang deprecated ?
(node:15972) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'queryExists')
    at __puppeteer_evaluation_script__:25:69
    at ExecutionContext._evaluateInternal (C:\laragon\www\chatgpt-wa-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\laragon\www\chatgpt-wa-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.initialize (C:\laragon\www\chatgpt-wa-bot\node_modules\whatsapp-web.js\src\Client.js:267:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Bangik** [comment]
Sepertinya library whatsapp web js nya deprecated

Mungkin bisa di coba solusi ini gan

https://github.com/pedroslopez/whatsapp-web.js/issues/1985#issuecomment-1423162508

Atau jika masih belum bisa, update versi whatsapp web jsnya ke yang terbaru

https://github.com/pedroslopez/whatsapp-web.js/releases/tag/v1.19.5
